### ISSUE TITLE
Backends as plugins

### ISSUE THREAD

**Issue by alexott** [SigmaHQ/sigma-cli#3]
Right now, there is a tight coupling between backends and sigma-cli. Although you're defining output formats in the backend, to use them with sigma-cli, you need to modify its code to add new output format(s). It would be easier if backend provided that information to sigma-cli, so no code modification is required.

**Comment by thomaspatzke** [comment]
Indeed&agreed! This was already the case with good old sigmatools and putting the descriptive information into the backends fits better there than in sigma-cli. I will move them over to the backends and keep this issue open for tracking until done.

**Comment by alexott** [comment]
Great! If necessary I can help with that.
It would be nice to automatically discover backends and pipelines as well. I’m looking for a ways of doing that

**Comment by thomaspatzke** [comment]
Autodiscovery was also [already there in sigmatools](https://github.com/SigmaHQ/sigma/blob/master/tools/sigma/backends/discovery.py).

In sigma-cli I wanted to make this explicit, because backends are external packages here. This makes it hard for the developer to spot, which backends are active there and there is a higher risk that something done in such a backend package could break the autodiscovery. While the monolithic architecture of sigmatools made these issues negligible, they're real for a modular setup like in sigma-cli.

And finally, the [Zen of Python](https://legacy.python.org/dev/peps/pep-0020/) states (`import this`):

> Explicit is better than implicit.

😉

**Comment by thomaspatzke** [comment]
Added it to the [backend base class](https://github.com/SigmaHQ/pySigma/blob/f85a30245558853540a7c247c026c70f416b4f91/sigma/conversion/base.py#L61) and to the [cookiecutter template](https://github.com/SigmaHQ/cookiecutter-pySigma-backend/blob/da1e058051859ef55673a6e2dea126e47b3fdbb1/%7B%7B%20cookiecutter.package_name%20%7D%7D/sigma/backends/%7B%7B%20cookiecutter.backend_package_name%20%7D%7D/%7B%7B%20cookiecutter.backend_package_name%20%7D%7D.py#L19).

**Comment by alexott** [comment]
explicit maybe could be better as advice, but right now to add a new backend I need to fork sigma-cli, hack its code, etc.  This make extension of it harder, especially in initial phases of development, or when using it for some internal tooling.

**Comment by Samrose-Ahmed** [comment]
A plugin system would be nice where a user could just do something like `<sigma add backend>` to add a backend. That would be explicit as well.

**Comment by thomaspatzke** [comment]
> A plugin system would be nice where a user could just do something like `sigma add <backend>` to add a backend. That would be explicit as well.

After some consideration I think this could be a really good idea because it solves the issue that Sigma CLI releases with major pySigma updates currently depend on the fact that all backends are on the same pySigma release. This adds an increased amount of coordination betwen contributors. This could especially get annoying if backends are abandoned or contributors start to get unresponsive for any reason.

**Comment by kelnage** [comment]
We're also currently in the process of finalising a release of a backend we have developed, and we were wondering if there was a ETA for the changes around including backends? We're happy to do a PR for `sigma-cli` in the meantime, but we would like to share our work in the near future if at all possible!

**Comment by thomaspatzke** [comment]
I've [already started](https://github.com/SigmaHQ/pySigma/tree/plugins) to make backends, pipelines and validators pluggable in pySigma. It needs some further work and integration into the CLI. Unfortunately my opensource time was a bit short in the last weeks, but starts to increase now again 😉 Therefore it's always hard for me to give an ETA, but it's in the top three of my Sigma todo list.

**Comment by vandir** [comment]
Please consider supporting config arguments of custom backends (ref: [base.py](https://github.com/SigmaHQ/pySigma/blob/main/sigma/conversion/base.py#L80)).

**Comment by thomaspatzke** [comment]
Just created the release for [pySigma 0.9.0](https://github.com/SigmaHQ/pySigma/releases/tag/v0.9.0) that provides a plugin system for backends, processing pipelines and validators. Already started to integrate this into Sigma CLI in the plugin branch. Backend and pipeline projects require some minor updates. Basically, the information contained in the CLI repository has moved to the plugins, as proposed by @alexott.

**Comment by thomaspatzke** [comment]
pySigma 0.9 is now integrated in the recent versions of Sigma CLI and backends/pipelines are now plugins that can be managed with the `sigma plugin` subcommand.

**Comment by alexott** [comment]
Thank you Thomas!
